/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gabriel.forms;

import gabriel.dao.ContatoDao;
import gabriel.logica.Contato;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabriel
 */
public class JAgenda extends javax.swing.JFrame {

    /**
     * Creates new form JAgenda
     */
    //DefaultTableModel e ListSelectionModel objetos p/ manipular uma tabela
    DefaultTableModel tmcontato = new DefaultTableModel(null, new String[]{"id", "nome", "endereco", "sexo", "telefone", "email"});
    List<Contato> contatos; //Minha coleçao de contatos
    ListSelectionModel lsmContato;

    public JAgenda() {  //Starta Jframe
        initComponents();
        DesabiliteCampos(); //Bloqueia os campos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLid = new javax.swing.JLabel();
        jLnome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTsex = new javax.swing.JTextField();
        jTid = new javax.swing.JTextField();
        jTnome = new javax.swing.JTextField();
        jTend = new javax.swing.JTextField();
        jTtel = new javax.swing.JTextField();
        jTema = new javax.swing.JTextField();
        jBpesquisa = new javax.swing.JButton();
        jTpesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelapai = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBnovo = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Contato"));

        jLid.setText("ID");

        jLnome.setText("Nome");

        jLabel3.setText("endereço");

        jLabel4.setText("telefone");

        jLabel5.setText("email");

        jLabel6.setText("sexo");

        jTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnome)
                    .addComponent(jLabel6)
                    .addComponent(jLid))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTema, jTend, jTid, jTnome, jTsex, jTtel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLnome)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, -1, 162));

        jBpesquisa.setText("Pesquisa");
        jBpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jBpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 31, -1, -1));

        jTpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(jTpesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 32, 449, -1));

        Tabelapai.setModel(tmcontato);
        Tabelapai.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmContato = Tabelapai.getSelectionModel();
        lsmContato.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    jTTableLinhaSelecionada(Tabelapai);
                }
            }
        });
        jScrollPane1.setViewportView(Tabelapai);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 530, 110));

        jBnovo.setText("novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBexcluir.setText("excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBalterar.setText("alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBsalvar.setText("salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBsair.setText("sair");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jBnovo)
                .addGap(60, 60, 60)
                .addComponent(jBalterar)
                .addGap(60, 60, 60)
                .addComponent(jBexcluir)
                .addGap(70, 70, 70)
                .addComponent(jBsalvar)
                .addGap(71, 71, 71)
                .addComponent(jBsair)
                .addGap(126, 126, 126))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBexcluir, jBnovo, jBsair, jBsalvar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBsair)
                    .addComponent(jBsalvar)
                    .addComponent(jBalterar)
                    .addComponent(jBexcluir)
                    .addComponent(jBnovo))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 252, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidActionPerformed

    private void jTpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpesquisaActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        HabiliteCampos(); //Desbloqueia os campos
        jTid.setText("");
        jTnome.setText("");
        jTema.setText("");
        jTsex.setText("");
        jTend.setText("");
        jTtel.setText("");
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
//Todos os botões necessitam de evento!No projeto GUI->Evento->Action       
        try {
            // TODO add your handling code here:
            aterarContato(); //Ao clicar no botão chama o metodo
            listarContatos();//Ao clicar no botão chama o metodo
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problema no jBalterar!" + ex);
        }
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        if (VerifiqueCampoVazio()) {//Um elemento só padrão TRUE,entao faça
            efetuarCadastro();// chama metodo
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            DesabiliteCampos(); //cadastra e bloqueia campo
        }

    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisaActionPerformed
        try {
            // TODO add your handling code here:
            listarContatos();// chama metodo
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro sql" + ex.getMessage());
        }
    }//GEN-LAST:event_jBpesquisaActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        try {
            // TODO add your handling code here:
            excluirContato();// chama metodo
            listarContatos();// chama metodo
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro!" + ex);
        }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        System.exit(0); //Sai do Jframe
    }//GEN-LAST:event_jBsairActionPerformed

    public boolean VerifiqueCampoVazio() {//Metodo p/tratamento de campo importante nao preenchido
        if (!jTnome.getText().equals("") && !jTend.getText().equals("")) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Calmpos 'Nome' e 'Tel' nao preenchidos!");
            return false;
        }
    }

    public void DesabiliteCampos() { //Desabilita campos do Jframe p/trabalho
        jTid.setEditable(false);
        jTnome.setEditable(false);
        jTsex.setEditable(false);
        jTtel.setEditable(false);
        jTend.setEditable(false);
        jTema.setEditable(false);
    }

    public void HabiliteCampos() { //habilita campos do Jframe p/trabalho
        jTnome.setEditable(true);
        jTsex.setEditable(true);
        jTtel.setEditable(true);
        jTend.setEditable(true);
        jTema.setEditable(true);
    }
//Para não encher os Botões com linhas de comando, crio metodos que se comunicam
//com o Banco e quando levados p/ os Botões devolvem uma Resposta
    protected void listarContatos() throws SQLException {
        ContatoDao Dao = new ContatoDao(); //Cria objeto da Classe ContatoDao
//Pega o q a pessoa digitou no campo pesquisa do Jframe, procura no Banco e retorna
//para o objeto List "contatos"
        contatos = Dao.getLista("%" + jTpesquisa.getText() + "%");
        mostrarPesquisa(contatos);//metodo que mostra os dados retornados pro List
        // na tabela

    }

    public void efetuarCadastro() {
        try {
            Contato c1 = new Contato(); //Instancia um cadastro
            c1.setNome(jTnome.getText()); //pega o que esta no campo do Jframe e
            //seta no argumento(variavel nome) referente..
            c1.setEndereco(jTend.getText());
            c1.setSexo(jTsex.getText());
            c1.setTelefone(jTtel.getText());
            c1.setEmail(jTema.getText());
            ContatoDao Dao = new ContatoDao();//chama Classe Banco

            Dao.adiciona(c1);// e usa o metodo para adicionar
        } catch (SQLException ex) {
            Logger.getLogger(JAgenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mostrarPesquisa(List<Contato> contatos) {//Não se comunica com o Banco
        while (tmcontato.getRowCount() > 0) {//Todo o processo é para ajustar os valores
            tmcontato.removeRow(0); //de pesquisa em uma tabela
        }
        if (contatos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum contato cadastrado!");

        } else {
            String[] linha = new String[]{null, null, null, null, null, null};
            for (int i = 0; i < contatos.size(); i++) {
                tmcontato.addRow(linha);
                tmcontato.setValueAt(contatos.get(i).getId(), i, 0);
                tmcontato.setValueAt(contatos.get(i).getNome(), i, 1);
                tmcontato.setValueAt(contatos.get(i).getEndereco(), i, 2);
                tmcontato.setValueAt(contatos.get(i).getSexo(), i, 3);
                tmcontato.setValueAt(contatos.get(i).getTelefone(), i, 4);
                tmcontato.setValueAt(contatos.get(i).getEmail(), i, 5);
            }
        }
    }

    private void jTTableLinhaSelecionada(JTable tabela) { 
        //seta os valores do List "contatos",nos os campos do Jframe 
        //é necessario passar um código padrão da tabela em GeneratedCode->InitComponents
        //Inserção do código em Projeto Jframe ->Propriedades->Codigo->codigo de pós-inicialização
        HabiliteCampos();                  
        if (Tabelapai.getSelectedRow() != -1) {
            jTid.setText(String.valueOf(contatos.get(tabela.getSelectedRow()).getId()));
            jTnome.setText(contatos.get(tabela.getSelectedRow()).getNome());
            jTend.setText(contatos.get(tabela.getSelectedRow()).getEndereco());
            jTsex.setText(contatos.get(tabela.getSelectedRow()).getSexo());
            jTtel.setText(contatos.get(tabela.getSelectedRow()).getTelefone());
            jTema.setText(contatos.get(tabela.getSelectedRow()).getEmail());
        } else {
            jTid.setText("");
            jTnome.setText("");
            jTend.setText("");
            jTsex.setText("");
            jTtel.setText("");
            jTema.setText("");
        }

    }

    public void excluirContato() throws SQLException {
        int pergunta = JOptionPane.showConfirmDialog(this, "Deseja excluir?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (pergunta == JOptionPane.YES_NO_OPTION) {
            ContatoDao Dao = new ContatoDao();
            Dao.Remove(contatos.get(Tabelapai.getSelectedRow()));
            mostrarPesquisa(contatos);
        }
    }

    public void aterarContato() throws SQLException {
        if (Tabelapai.getSelectedRow() != -1) {
            if (VerifiqueCampoVazio()) {
                Contato c1 = new Contato();
                ContatoDao Dao = new ContatoDao();

                c1.setId(Integer.valueOf(jTid.getText()));
                c1.setNome(jTnome.getText());
                c1.setEndereco(jTend.getText());
                c1.setSexo(jTsex.getText());
                c1.setTelefone(jTtel.getText());
                c1.setEmail(jTema.getText());
                Dao.Altera(c1);
                JOptionPane.showMessageDialog(null, "Alterado com sucesso!");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAgenda().setVisible(true);
            }
        });
    }
    /* Declaração Variaveis*/
    //<editor-fold defaultstate="collapsed" desc=" Declaração Variaveis (optional) ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabelapai;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBpesquisa;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLid;
    private javax.swing.JLabel jLnome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTema;
    private javax.swing.JTextField jTend;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTsex;
    private javax.swing.JTextField jTtel;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
}